import { Geist, Geist_Mono } from "next/font/google";
import { ModalProvider } from "@/Context/ModalContext";
import Modal from "../components/Modal/Modal";
import { MenuProvider } from "@/Context/MenuContext";
import Menu from "../components/Menu/Menu";
import UTMCookieSaver from "@/components/UTMCookieSaver/UTMCookieSaver";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <UTMCookieSaver>
          <ModalProvider>
            <MenuProvider>
              {children}
              <Menu />
              <Modal />
            </MenuProvider>
          </ModalProvider>
        </UTMCookieSaver>
      </body>
    </html>
  );
}
