import { Geist, Geist_Mono } from "next/font/google";
import { ModalProvider } from "@/Context/ModalContext";
import Modal from "../components/Modal/Modal";
import { MenuProvider } from "@/Context/MenuContext";

import UTMCookieSaver from "@/components/UTMCookieSaver/UTMCookieSaver";
import localFont from "next/font/local";
import "./globals.css";

const MontserratBold = localFont({
  src: "../public/fonts/Montserrat-Bold.ttf",
  weight: "800",
  variable: "--font-montserrat",
});

const MontserratSemiBold = localFont({
  src: "../public/fonts/Montserrat-SemiBold.ttf",
  weight: "700",
  variable: "--font-montserrat",
});

const MontserratMedium = localFont({
  src: "../public/fonts/Montserrat-Medium.ttf",
  weight: "600",
  variable: "--font-montserrat",
});

const MontserratRegular = localFont({
  src: "../public/fonts/Montserrat-Regular.ttf",
  weight: "400",
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${MontserratRegular.variable} ${MontserratMedium.variable} ${MontserratSemiBold.variable} ${MontserratBold.variable}`}
      >
        <UTMCookieSaver />
        <ModalProvider>
          <MenuProvider>
            {children}
            <Modal />
          </MenuProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
